version: '3.8'
services:
 dynamodb-local:
   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb-local
   ports:
     - "8000:8000"
   volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal
   environment:
    AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
    AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
#  app-node:
#    depends_on:
#      - dynamodb-local
#    image: amazon/aws-cli
#    container_name: app-node
#    ports:
#     - "8080:8080"
#    environment:
#      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
#      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
#    command:
#      dynamodb describe-limits --endpoint-url http://dynamodb-local:8000 --region ap-northeast-2